In [1]:
import pandas as pd
import matplotlib.pylab as plt
from datetime import datetime
plt.style.use('fivethirtyeight')
%matplotlib inline

In [2]:
df = pd.read_csv('./seattle-library-checkout-records/most_checked_out_all.csv')
print(len(df))

5484915

In [3]:
df.head()

,Unnamed: 0,author,description,format_subgroup,num_checkouts,publication_year,publisher,title,year
0,0,NaN,DVD: Adult/YA,Video Disc,2564,[2006],Touchstone Home Entertainment : Distributed by...,Flightplan [videorecording] / Touchstone Pictu...,2006
1,1,NaN,DVD: Adult/YA,Video Disc,2564,[2006],Touchstone Home Entertainment : Distributed by...,Flightplan / Touchstone Pictures and Imagine E...,2006
2,2,NaN,DVD: Adult/YA,Video Disc,2341,[2006],"Distributed by Universal Pictures,",Broken flowers [videorecording] / Bac Films ; ...,2006
3,3,NaN,DVD: Adult/YA,Video Disc,2341,[2006],"Distributed by Universal Pictures,",Broken flowers / Bac Films ; Focus Features ; ...,2006
4,4,NaN,DVD: Adult/YA,Video Disc,2316,c2005.,"Warner Home Video,",March of the penguins [videorecording] / Bonne...,2006

In [4]:
def top_list(year, format_subgroup, k=5):
    top = df[df['year']==year][df['format_subgroup'].apply(lambda x: x in format_subgroup)].sort_values(by = 'num_checkouts', ascending = False)
    return top[['author','title','publication_year','num_checkouts']].head(k)

In [5]:
top_list(2019, ['Video Disc','Audio Disc', 'Music Score'], k=10)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,author,title,publication_year,num_checkouts
4488210,NaN,The shape of water / Fox Searchlight Pictures ...,[2018],2963
4488219,NaN,"Three billboards outside Ebbing, Missouri / Fo...",[2018],2825
4488224,NaN,Coco / Disney ; Pixar Animation Studios ; orig...,[2018],2704
4488242,NaN,Dunkirk / Warner Bros. Pictures ; Syncopy ; pr...,[2017],2581
4488243,NaN,Blade runner 2049 / Warner Bros. Pictures ; Al...,[2018],2568
4488251,NaN,Darkest hour / Focus Features ; Perfect World ...,[2018],2426
4488252,NaN,Lady Bird / A24 and IAC Films ; produced by Sc...,[2018],2391
4488253,NaN,Black Panther / Marvel Studios ; produced by K...,2018.,2359
4488260,NaN,"I, Tonya / Neon ; 30West ; AI Film ; Bein Medi...",[2018],2283
4488286,NaN,Phantom thread / Focus Features ; Annapurna Pi...,[2018],2149

In [6]:
top_list(2018, ['Book'], k=20).drop_duplicates()

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,author,title,publication_year,num_checkouts
4488153,"Westover, Tara",Educated : a memoir / Tara Westover.,[2018],5059
4488156,"Thomas, Angie",The hate u give / Angie Thomas.,[2017],4919
4488159,"Oluo, Ijeoma.",So you want to talk about race / Ijeoma Oluo.,2018.,4663
4488162,"Oluo, Ijeoma",So you want to talk about race / Ijeoma Oluo.,2018.,4663
4488164,"Alderman, Naomi",The power : a novel / Naomi Alderman.,2017.,4365
4488165,"Finn, A. J.",The woman in the window / A.J. Finn.,[2018],4192
4488167,"Lee, Min Jin",Pachinko / Min Jin Lee.,2017.,4004
4488169,"Jones, Tayari",An American marriage : a novel / by Tayari Jones.,2018.,3977
4488170,"Jones, Tayari",An American marriage / a novel by Tayari Jones.,2018.,3977

In [9]:
for year in range(2006,2020):
    print('=======================================================================================')
    print(year)
    for format in [['Book'], ['Video Disc','Audio Disc', 'Music Score']]:
        print(format)
        print('=========')
        print(top_list(year, format, k=1))
    print('=======================================================================================')

=======================================================================================
2006
['Book']
=========

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

                author                                              title  \
83  Maslen, Bobby Lynn  Bob books first! / text, Bobby Lynn Maslen ; p...

   publication_year  num_checkouts
83   [2000], c1976.           1547
['Video Disc', 'Audio Disc', 'Music Score']
=========
  author                                              title publication_year  \
0    NaN  Flightplan [videorecording] / Touchstone Pictu...           [2006]

   num_checkouts
0           2564
=======================================================================================
=======================================================================================
2007
['Book']
=========
       author                           title publication_year  num_checkouts
207383    NaN  Uncataloged Folder or Bag--DWN              NaN           1906
['Video Disc', 'Audio Disc', 'Music Score']
=========
       author                                              title  \
207372    NaN  Little Miss Sunshine [videorecording] / Big Be...

       publication_year  num_checkouts
207372           c2006.           2335
=======================================================================================
=======================================================================================
2008
['Book']
=========
       author                           title publication_year  num_checkouts
433511    NaN  Uncataloged Folder or Bag--DWN              NaN           1772
['Video Disc', 'Audio Disc', 'Music Score']
=========
       author                                              title  \
433340    NaN  Michael Clayton [videorecording] / Warner Bros...

       publication_year  num_checkouts
433340           [2008]           4957
=======================================================================================
=======================================================================================
2009
['Book']
=========
       author                                              title  \
686748    NaN  Tropic thunder [videorecording] / DreamWorks ;...

       publication_year  num_checkouts
686748           c2008.           3981
['Video Disc', 'Audio Disc', 'Music Score']
=========
       author                                              title  \
686698    NaN  Burn after reading [videorecording] / Focus Fe...

       publication_year  num_checkouts
686698           c2008.           6152
=======================================================================================
=======================================================================================
2010
['Book']
=========
       author                                              title  \
974373    NaN  Tropic thunder [videorecording] / DreamWorks ;...

       publication_year  num_checkouts
974373           c2008.           2814
['Video Disc', 'Audio Disc', 'Music Score']
=========
       author                                              title  \
974246    NaN  Doubt [videorecording] / Miramax Films ; produ...

       publication_year  num_checkouts
974246           [2009]           5428
=======================================================================================
=======================================================================================
2011
['Book']
=========
                    author                         title publication_year  \
1292622  Stockett, Kathryn  The help / Kathryn Stockett.           c2009.

         num_checkouts
1292622           2061
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
1292482    NaN  Up in the air [videorecording] / Paramount ; T...

        publication_year  num_checkouts
1292482           [2010]           3149
=======================================================================================
=======================================================================================
2012
['Book']
=========
                   author                                title  \
1642810  Collins, Suzanne  The hunger games / Suzanne Collins.

        publication_year  num_checkouts
1642810   [2009], c2008.           2018
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
1642713    NaN  Moneyball [videorecording] / Columbia Pictures...

        publication_year  num_checkouts
1642713           [2012]           2684
=======================================================================================
=======================================================================================
2013
['Book']
=========
                author                                              title  \
2026610  Semple, Maria  Where'd you go, Bernadette : a novel / Maria S...

        publication_year  num_checkouts
2026610            2012.           3977
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
2026608    NaN  Argo [videorecording] / Warner Bros. ; GK Film...

        publication_year  num_checkouts
2026608            2013.           4649
=======================================================================================
=======================================================================================
2014
['Book']
=========
               author                         title publication_year  \
2459279  Tartt, Donna  The goldfinch / Donna Tartt.            2013.

         num_checkouts
2459279           2919
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
2459249    NaN  American hustle [videorecording] / Columbia Pi...

        publication_year  num_checkouts
2459249           [2014]           4190
=======================================================================================
=======================================================================================
2015
['Book']
=========
                 author                                   title  \
2924334  Hawkins, Paula  The girl on the train / Paula Hawkins.

        publication_year  num_checkouts
2924334            2015.           2721
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
2924305    NaN  Gone girl [videorecording] / Twentieth Century...

        publication_year  num_checkouts
2924305           [2015]           4375
=======================================================================================
=======================================================================================
2016
['Book']
=========
                 author                                   title  \
3421186  Hawkins, Paula  The girl on the train / Paula Hawkins.

        publication_year  num_checkouts
3421186            2015.           2096
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
3421120    NaN  The Martian [videorecording] / Twentieth Centu...

        publication_year  num_checkouts
3421120           [2015]           4137
=======================================================================================
=======================================================================================
2017
['Book']
=========
                           author  \
3944303  Whitehead, Colson, 1969-

                                                     title publication_year  \
3944303  The Underground Railroad : a novel / Colson Wh...           [2016]

         num_checkouts
3944303           2621
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
3944294    NaN  Arrival / Paramount Pictures ; Filmnation Ente...

        publication_year  num_checkouts
3944294           [2017]           3687
=======================================================================================
=======================================================================================
2018
['Book']
=========

                 author                                 title  \
4488153  Westover, Tara  Educated : a memoir / Tara Westover.

        publication_year  num_checkouts
4488153           [2018]           5059
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
4488210    NaN  The shape of water / Fox Searchlight Pictures ...

        publication_year  num_checkouts
4488210           [2018]           2963
=======================================================================================
=======================================================================================
2019
['Book']
=========
                         author                       title publication_year  \
5024885  Obama, Michelle, 1964-  Becoming / Michelle Obama.           [2018]

         num_checkouts
5024885           5287
['Video Disc', 'Audio Disc', 'Music Score']
=========
        author                                              title  \
5024955    NaN  Green book / Universal ; Participant Media ; D...

        publication_year  num_checkouts
5024955           [2019]           2091
=======================================================================================

In [12]:
top_list(2007, ['Video Disc','Audio Disc', 'Music Score'], 11)['title']

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

207372    Little Miss Sunshine [videorecording] / Big Be...
207373    Little Miss Sunshine / Big Beach Films ; Third...
207374    The constant gardener [videorecording] / Potbo...
207375    The constant gardener / Potboiler Productions ...
207377    The Black Dahlia [videorecording] / Millennium...
207378    The Black Dahlia / Millennium Films ; Signatur...
207379    Broken flowers [videorecording] / Bac Films ; ...
207380    Broken flowers / Bac Films ; Focus Features ; ...
207381    In her shoes [videorecording] / In Her Shoes c...
207382    In her shoes / In Her Shoes c/o The Lot ; Scot...
207386    Good night, and good luck [videorecording] / W...
Name: title, dtype: object

In [13]:
top_list(2008, ['Book'], 11)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,author,title,publication_year,num_checkouts
433511,NaN,Uncataloged Folder or Bag--DWN,NaN,1772
433570,"Pollan, Michael",In defense of food : an eater's manifesto / Mi...,2008.,1579
433640,"McMullan, Kate",I stink! / Kate & Jim McMullan.,c2002.,1411
433641,"McMullan, Kate",I stink! / Kate & Jim McMullan.,[2002],1411
433657,"Martin, Bill, 1916-2004","Chicka chicka boom boom / by Bill Martin, Jr. ...",c1989.,1375
433658,"Martin, Bill, 1916-2004","Chicka chicka boom boom / by Bill Martin, Jr. ...",[1989],1375
433663,"Mortenson, Greg",Three cups of tea : one man's mission to fight...,2006.,1364
433664,"Mortenson, Greg",Three cups of tea : one man's mission to fight...,2006.,1364
433665,"Hosseini, Khaled",A thousand splendid suns / Khaled Hosseini.,2007.,1361
433668,"McLeod, Bob",SuperHero ABC / by Bob McLeod.,2006.,1355
433673,"Maslen, Bobby Lynn",Bob books fun! / by Bobby Lynn Maslen ; pictur...,1999.,1352